Full angular removal
NASA-AMMOS/openmct-mcws pull request #170
Opened 2024-04-19 01:50 UTC by jvigliotta

2024-04-29 21:20 UTC, davetsay commented on loader.js
> -    'openmct-legacy-support',
Daaaaayum

2024-04-30 18:07 UTC, davetsay requested changes
Wow good stuff. That's a bunch of work. I made some suggestions and had some questions.

- [x] I think we should just be consistent and remove the `this._openmct` references.
- [ ] We may want to file a follow up to improve venues, but should first find out how they really should work properly.
- [ ] Do any unit tests need updating?
- [ ] One thing i know was used in legacy repo, was the Data Product viewer, so let's test that.

2024-04-30 19:24 UTC, davetsay commented on src/exportDataAction/ExportDataAction.js
> +        const hasComposition = this._openmct.composition.get(domainObject) !== undefined;
So the plan is to add container type objects to the appliesTo if not there (tables, plots), and then to do a full check in invoke and let the user know if the data is non-exportable or not.

2024-05-01 21:23 UTC, jvigliotta commented on src/exportDataAction/ExportDataTask.js
> +        const pullHeaders = (dataArray) => {
fo sho!

2024-05-03 19:45 UTC, jvigliotta commented on src/venues/Venue.js
> +const DATASET_FIELDS = [
I pulled in what was in the constants from datasets and kept anything that wasn't included in that but existed here.

2024-05-03 19:47 UTC, jvigliotta commented on src/legacy/export/src/ExportDataTask.js
> -                telemetry.requestData({ strategy: 'comprehensive' }) :
I've re-added it to the new code.

2024-05-03 21:08 UTC, jvigliotta commented
Follow up issues:
Update Tests: https://github.com/NASA-AMMOS/openmct-mcws/issues/172
Optimize Venue Pllugin: https://github.com/NASA-AMMOS/openmct-mcws/issues/173

2024-05-03 22:02 UTC, davetsay requested changes
i think the valid types thing is the only thing that needs fixing

2024-05-03 22:02 UTC, davetsay commented on src/venues/Venue.js
> +];
does some stuff need to be back ported into the constants file?

2024-05-03 22:16 UTC, jvigliotta commented on src/exportDataAction/ExportDataAction.js
>          return hasHistoricalTelemetry || !hasHistoricalTelemetry && hasComposition;
yep... my bad. Updated!

2024-05-03 23:26 UTC, davetsay approved these changes
Great work @jvigliotta . We finally did it!

2024-05-03 23:28 UTC, merged