Added ability to deny unfiltered historical queries if new config opt…
NASA-AMMOS/openmct-mcws pull request #176
Opened 2024-05-08 13:01 UTC by chesterhawkins

closes #175 

New config option sessions.historicalSessionFilter. denyUnfilteredQueries is used to determine whether an unfiltered historical query should be denied or allowed.

2024-07-25 23:34 UTC, jvigliotta requested changes
This looks great! Can we change the double quotes to single quotes for the message (we're trying to stick to this moving forward)? Also, can we update the config to add the new option, but default it to false.

2024-08-13 23:14 UTC, davetsay requested changes
Hi @chesterhawkins . thanks so much for contributing. I have one more slight change. I added a code suggestion to also check for the `disable` prop not being true. If it is false we shouldn't care about the `denyUnfilteredQueries` prop.

2024-08-13 23:14 UTC, davetsay commented on src/historical/HistoricalProvider.js
> +        } else if (window.openmctMCWSConfig?.sessions?.historicalSessionFilter?.denyUnfilteredQueries === true) {
```suggestion
        } else if (window.openmctMCWSConfig?.sessions?.historicalSessionFilter?.disable !== true && window.openmctMCWSConfig?.sessions?.historicalSessionFilter?.denyUnfilteredQueries === true) {
```

2024-08-14 01:14 UTC, davetsay approved these changes
Awesome. Thanks, @chesterhawkins

2024-08-14 01:15 UTC, jvigliotta approved these changes
LGTM!

2024-08-14 01:16 UTC, merged